# Generated by Django 6.0.6 on 2026-06-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='observaciones',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('asistentes_esperados', models.IntegerField()),
                ('asistentes_reales', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('requerimientos', models.TextField(blank=True)),
                ('salas', models.ManyToManyField(to='reservaciones.sala')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaciones.solicitud')),
            ],
        ),
    ]
