# Generated by Django 6.0.6 on 2026-06-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0002_alter_solicitud_observaciones_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AddField(
            model_name='evento',
            name='color',
            field=models.CharField(default='#3788d8', max_length=7),
        ),
    ]
